### ISSUE TITLE
Feat: Implement Dashboard Chart section

### ISSUE THREAD

**Issue by jkarenzi** [atlp-rwanda/dynamites-ecomm-fe#73]
## Description
- As an admin, I want to be able to see chart data about visitor insights and top categories, so that I can know how the ecommerce platform is performing.

## Tasks
- [ ] Design the chart in accordance with the figma design
- [ ] Fetch relevant data from backend and integrate it with the chart

## Definition of Done
- Admin can see visitor insights chart
- Admin can see information about top categories
- Chart data is fetched from the backend

**Comment by jkarenzi** [comment]
## Implementation plan

### Day 1
- Conduct extensive research on how to implement charts in react

### Day 2
- Start implementing the chart

### Day 3
- Fetch chart data from backend

**Comment by EddyShimwa** [comment]
## Implementation plan
### Day 1
- Add the endpoint on backend since they are not implemented
### Day 2
- Start integration of endpoint and implementing figma design
